/* A RapidNet application. Generated by RapidNet compiler. */

#ifndef PACKETFORWARD_H
#define PACKETFORWARD_H

#include <string>
#include <iostream>
#include "ns3/ptr.h"
#include "ns3/event-id.h"
#include "ns3/ipv4-address.h"
#include "ns3/rapidnet-header.h"
#include "ns3/relation-base.h"
#include "ns3/database.h"
#include "ns3/rapidnet-application-base.h"
#include "ns3/aggregator.h"
#include "ns3/aggwrap.h"

using namespace std;
using namespace ns3;

namespace ns3 {

class Socket;
class Packet;

namespace rapidnet {
namespace packetforward {

class PacketForward : public RapidNetApplicationBase
{
public:
  static const string EDGE;
  static const string EDGECOUNT;
  static const string EPACKET;
  static const string ERECV;
  static const string INSERTEDGE;
  static const string PACKET;
  static const string PROV;
  static const string R1_4EPACKETL;
  static const string RECV;
  static const string ROUTE;

  static TypeId GetTypeId (void);

  PacketForward ();

  virtual ~PacketForward ();

protected:

  virtual void DoDispose (void);

  virtual void StartApplication (void);

  virtual void StopApplication (void);

  virtual void InitDatabase (void);

  virtual void DemuxRecv (Ptr<Tuple> tuple);

  virtual void R1_1Eca0Ins (Ptr<Tuple> packet);

  virtual void R1_1Eca1Ins (Ptr<Tuple> route);

  virtual void R1_2_eca (Ptr<Tuple> epacket);

  virtual void R1_3_eca (Ptr<Tuple> epacket);

  virtual void R1_4Local1_eca (Ptr<Tuple> epacket);

  virtual void R1_4Local2_eca (Ptr<Tuple> r1_4epacketL);

  virtual void R2_1Eca0Ins (Ptr<Tuple> packet);

  virtual void R2_2_eca (Ptr<Tuple> erecv);

  virtual void R2_3_eca (Ptr<Tuple> erecv);

  virtual void R2_4_eca (Ptr<Tuple> erecv);

  virtual void Re_1_eca (Ptr<Tuple> insertedge);

  virtual void Re_2_eca (Ptr<Tuple> edgeCount);

  virtual void Re_3_eca (Ptr<Tuple> edgeCount);

};

} // namespace packetforward
} // namespace rapidnet
} // namespace ns3

#endif // PACKETFORWARD_H
