/* A RapidNet application. Generated by RapidNet compiler. */

#ifndef PACKETFORWARD_H
#define PACKETFORWARD_H

#include <string>
#include <iostream>
#include "ns3/ptr.h"
#include "ns3/event-id.h"
#include "ns3/ipv4-address.h"
#include "ns3/rapidnet-header.h"
#include "ns3/relation-base.h"
#include "ns3/database.h"
#include "ns3/rapidnet-application-base.h"
#include "ns3/aggregator.h"
#include "ns3/aggwrap.h"

using namespace std;
using namespace ns3;

namespace ns3 {

class Socket;
class Packet;

namespace rapidnet {
namespace packetforward {

class PacketForward : public RapidNetApplicationBase
{
public:
  static const string PACKET;
  static const string PACKETDELETE;
  static const string R1PACKETSEND;
  static const string RECV;
  static const string ROUTE;

  static TypeId GetTypeId (void);

  PacketForward ();

  virtual ~PacketForward ();

protected:

  virtual void DoDispose (void);

  virtual void StartApplication (void);

  virtual void StopApplication (void);

  virtual void InitDatabase (void);

  virtual void DemuxRecv (Ptr<Tuple> tuple);

  virtual void R1Eca0RemoteIns (Ptr<Tuple> r1packetsend);

  virtual void R1Eca0RemoteDel (Ptr<Tuple> packetDelete);

  virtual void R1Eca0Ins (Ptr<Tuple> packet);

  virtual void R1Eca0Del (Ptr<Tuple> packet);

  virtual void R1Eca1Ins (Ptr<Tuple> route);

  virtual void R1Eca1Del (Ptr<Tuple> route);

  virtual void R2Eca0Ins (Ptr<Tuple> packet);

  virtual void R2Eca0Del (Ptr<Tuple> packet);

};

} // namespace packetforward
} // namespace rapidnet
} // namespace ns3

#endif // PACKETFORWARD_H
