## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('packet-forward', ['internet-stack'])
    module.source = [
        'packet-forward.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'packet-forward'
    headers.source = [
        'packet-forward.h',
        'packet-forward-helper.h',
        ]
