/* A RapidNet application. Generated by RapidNet compiler. */

#ifndef SMOKE_H
#define SMOKE_H

#include <string>
#include <iostream>
#include "ns3/ptr.h"
#include "ns3/event-id.h"
#include "ns3/ipv4-address.h"
#include "ns3/rapidnet-header.h"
#include "ns3/relation-base.h"
#include "ns3/database.h"
#include "ns3/rapidnet-application-base.h"
#include "ns3/aggregator.h"
#include "ns3/aggwrap.h"

using namespace std;
using namespace ns3;

namespace ns3 {

class Socket;
class Packet;

namespace rapidnet {
namespace smoke {

class Smoke : public RapidNetApplicationBase
{
public:
  static const string CANCER;
  static const string ECANCER;
  static const string EDGE;
  static const string EDGECOUNT;
  static const string ESMOKE;
  static const string FRIENDS;
  static const string INSERTEDGE;
  static const string PROV;
  static const string SHARESULT;
  static const string SMOKE;

  static TypeId GetTypeId (void);

  Smoke ();

  virtual ~Smoke ();

protected:

  virtual void DoDispose (void);

  virtual void StartApplication (void);

  virtual void StopApplication (void);

  virtual void InitDatabase (void);

  virtual void DemuxRecv (Ptr<Tuple> tuple);

  virtual void R1_1Eca0Ins (Ptr<Tuple> smoke);

  virtual void R1_2_eca (Ptr<Tuple> ecancer);

  virtual void R1_3_eca (Ptr<Tuple> ecancer);

  virtual void R1_4_eca (Ptr<Tuple> ecancer);

  virtual void R2_1Eca0Ins (Ptr<Tuple> friends);

  virtual void R2_1Eca2Ins (Ptr<Tuple> smoke);

  virtual void R2_2_eca (Ptr<Tuple> esmoke);

  virtual void R2_3_eca (Ptr<Tuple> esmoke);

  virtual void R2_4_eca (Ptr<Tuple> esmoke);

  virtual void R3_1Eca0Ins (Ptr<Tuple> friends);

  virtual void R3_1Eca2Ins (Ptr<Tuple> smoke);

  virtual void Re_1_eca (Ptr<Tuple> insertedge);

  virtual void Re_2_eca (Ptr<Tuple> edgeCount);

  virtual void Re_3_eca (Ptr<Tuple> edgeCount);

  virtual void R11Eca0Ins (Ptr<Tuple> smoke);

  virtual void R11Eca0Del (Ptr<Tuple> smoke);

  virtual void R12Eca0Ins (Ptr<Tuple> cancer);

  virtual void R12Eca0Del (Ptr<Tuple> cancer);

  virtual void R13Eca0Ins (Ptr<Tuple> friends);

  virtual void R13Eca0Del (Ptr<Tuple> friends);

};

} // namespace smoke
} // namespace rapidnet
} // namespace ns3

#endif // SMOKE_H
