## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('trust-prob', ['internet-stack'])
    module.source = [
        'trust-prob.cc',
        ]
    headers = bld.new_task_gen('ns3header')
    headers.module = 'trust-prob'
    headers.source = [
        'trust-prob.h',
        'trust-prob-helper.h',
        ]
